#!/bin/bash

echo ">>> Installing cube4health"
pip install --no-deps git+https://github.com/Harmonize-Brazil/cube4health.git@main

echo ">>> Preparing Jupyter environment"

# Ensure the environment's kernel appears in JupyterLab
python -m ipykernel install --user --name cube4health-binder --display-name "Cube4Health (Binder)"

# Pre-build Matplotlib font cache
python - <<EOF
import matplotlib
matplotlib.get_cachedir()
EOF

echo ">>> Binder postBuild completed"
